'use client';
import { useEffect, useState } from 'react'; import type React from 'react'; import { useRouter } from 'next/navigation';
type Row=Record<string,unknown>; const tabs=['Dashboard','Bookings','Providers','Customers','Services','Payments','Support'];
const money=(n:unknown)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n||0));
export default function Console(){const router=useRouter();const [tab,setTab]=useState('Dashboard');const [data,setData]=useState<unknown>(null);const [error,setError]=useState('');const endpoints:Record<string,string>={Dashboard:'admin/dashboard',Bookings:'admin/bookings',Providers:'admin/providers',Customers:'admin/customers',Services:'admin/catalog',Payments:'admin/payments',Support:'support'};
async function load(){setError('');try{const r=await fetch(`/api/proxy/${endpoints[tab]}`,{cache:'no-store'});if(r.status===401||r.status===403){router.replace('/login');return}const d=await r.json().catch(()=>({detail:'The API returned an unreadable response'}));if(!r.ok)setError(d.detail||'Unable to load operations data');else setData(d)}catch{setError('Unable to reach the Haazir API. Try again.')}} // eslint-disable-next-line react-hooks/exhaustive-deps
useEffect(()=>{setData(null);void load()},[tab]);
async function patch(path:string,body:Row){try{const r=await fetch(`/api/proxy/${path}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!r.ok){const d=await r.json().catch(()=>({detail:'The API returned an unreadable response'}));setError(d.detail||'Action failed')}else void load()}catch{setError('Unable to reach the Haazir API. Try again.')}}
async function logout(){await fetch('/api/logout',{method:'POST'});router.replace('/login')}
return <div className="shell"><aside><div className="logo"><b>H</b><span>HAAZIR<small>OPERATIONS</small></span></div><nav>{tabs.map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</nav><div className="aside-foot"><span className="pulse"/>Systems console<button onClick={logout}>Sign out</button></div></aside><main><header><div><small>MARKETPLACE CONTROL</small><h1>{tab}</h1></div><button className="refresh" onClick={load}>Refresh data</button></header>{error&&<div className="error">{error}</div>} {!data?<div className="loading">Loading live operations data…</div>:<View tab={tab} data={data} patch={patch}/>}</main></div>}
function View({tab,data,patch}:{tab:string,data:unknown,patch:(p:string,b:Row)=>void}){if(tab==='Dashboard'){const d=data as Row;const counts=d.status_counts as Row;return <><div className="metric-grid"><Metric label="Bookings today" value={d.bookings_today}/><Metric label="Active providers" value={d.active_providers}/><Metric label="Online providers" value={d.online_providers}/><Metric label="Pending verification" value={d.pending_provider_verification} alert/></div><section><h2>Booking pulse</h2><div className="status-grid">{Object.entries(counts).map(([k,v])=><Metric key={k} label={k.replaceAll('_',' ')} value={v}/>)}</div></section><section><h2>Today’s economics</h2><div className="metric-grid"><Metric label="Gross booking value" value={money(d.gross_booking_value)}/><Metric label="Platform commission" value={money(d.platform_commission)}/><Metric label="Provider earnings" value={money(d.provider_earnings)}/></div></section></>}
if(tab==='Services'){const d=data as {categories:Row[],services:Row[]};return <><Table title="Service categories" rows={d.categories} columns={['name','slug','is_active','display_order']} actions={r=><button onClick={()=>patch(`admin/categories/${r.id}`,{is_active:!r.is_active})}>{r.is_active?'Deactivate':'Activate'}</button>}/><Table title="Server-authoritative services" rows={d.services} columns={['name','slug','base_visit_charge','min_charge','emergency_surcharge_rate','estimated_duration_mins','is_active']} actions={r=><button onClick={()=>patch(`admin/services/${r.id}`,{is_active:!r.is_active})}>{r.is_active?'Deactivate':'Activate'}</button>}/></>}
const rows=data as Row[];if(tab==='Providers')return <Table title="Provider verification & availability" rows={rows} columns={['business_name','verification_status','rating_average','completed_jobs_count','service_radius_km','is_online','is_available']} actions={r=><><button onClick={()=>patch(`admin/providers/${r.id}/verify`,{verification_status:'VERIFIED'})}>Verify</button><button className="danger" onClick={()=>patch(`admin/providers/${r.id}/verify`,{verification_status:'REJECTED'})}>Reject</button><button className="danger" onClick={()=>patch(`admin/users/${r.user_id}`,{is_suspended:!(r.user as Row).is_suspended})}>{(r.user as Row).is_suspended?'Reactivate':'Suspend'}</button></>}/>;
if(tab==='Customers')return <Table title="Customer accounts" rows={rows} columns={['full_name','phone','email','booking_count','is_active','is_suspended']} actions={r=><button className="danger" onClick={()=>patch(`admin/users/${r.id}`,{is_suspended:!r.is_suspended})}>{r.is_suspended?'Reactivate':'Suspend'}</button>}/>;
if(tab==='Bookings')return <Table title="Booking operations — read-only lifecycle" rows={rows} columns={['booking_number','status','customer_id','provider_id','service_id','created_at','cancellation_reason']}/>;
if(tab==='Payments')return <Table title="Cash/basic payment ledger" rows={rows} columns={['booking_number','payment_method','status','amount','platform_commission','provider_earning','completed_at']}/>;
return <Table title="Support cases" rows={rows} columns={['issue_type','description','status','booking_id','raised_by_user_id','resolution_notes','created_at']} actions={r=><button onClick={()=>patch(`support/${r.id}`,{status:r.status==='RESOLVED'?'OPEN':'RESOLVED',resolution_notes:r.status==='RESOLVED'?null:'Resolved by operations'})}>{r.status==='RESOLVED'?'Reopen':'Resolve'}</button>}/>}
function Metric({label,value,alert}:{label:string,value:unknown,alert?:boolean}){return <div className={`metric ${alert?'alert':''}`}><span>{label}</span><strong>{String(value??0)}</strong></div>}
function Table({title,rows,columns,actions}:{title:string,rows:Row[],columns:string[],actions?:(r:Row)=>React.ReactNode}){const [filter,setFilter]=useState('');const visible=rows.filter(r=>columns.some(c=>String(r[c]??'').toLowerCase().includes(filter.toLowerCase())));return <section><div className="section-head"><h2>{title}</h2><div><input className="filter" value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Filter records…"/><span>{visible.length} records</span></div></div><div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{c.replaceAll('_',' ')}</th>)}{actions&&<th>Actions</th>}</tr></thead><tbody>{visible.length===0?<tr><td colSpan={columns.length+1}>No records found.</td></tr>:visible.map((r,i)=><tr key={String(r.id||i)}>{columns.map(c=><td key={c}>{typeof r[c]==='boolean'?(r[c]?'Yes':'No'):c.includes('amount')||c.includes('earning')||c.includes('commission')?money(r[c]):String(r[c]??'—')}</td>)}{actions&&<td className="actions">{actions(r)}</td>}</tr>)}</tbody></table></div></section>}
